#!/usr/bin/env bash

set -euo pipefail

ENV_FILE="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/.env"
PROXY_ENV="$HOME/.proxy.env"
M2_SETTINGS="$HOME/.m2/settings.xml"
GENERATED_MARK="GENERATED by .devcontainer/setup-proxy.sh"

get() { grep -m1 "^$1=" "$ENV_FILE" 2>/dev/null | cut -d= -f2- || true; }
HTTP_PROXY="$(get HTTP_PROXY)"
NO_PROXY="$(get NO_PROXY)"

for rc in "$HOME/.bashrc" "$HOME/.zshrc"; do
  touch "$rc"
  grep -qF '.proxy.env' "$rc" \
    || printf '\n[ -f "$HOME/.proxy.env" ] && . "$HOME/.proxy.env"\n' >> "$rc"
done

if [ -z "$HTTP_PROXY" ]; then
  : > "$PROXY_ENV"
  if [ -f "$M2_SETTINGS" ] && grep -qF "$GENERATED_MARK" "$M2_SETTINGS"; then
    rm -f "$M2_SETTINGS"
  fi
  echo "[setup-proxy] no HTTP_PROXY in $ENV_FILE — proxy-less setup, no $M2_SETTINGS"
  exit 0
fi

NO_PROXY="${NO_PROXY:-localhost,127.0.0.1}"

# http://host:port → host, port
hostport="${HTTP_PROXY#*://}"
hostport="${hostport%%/*}"
host="${hostport%%:*}"
port="${hostport##*:}"

nph=",${NO_PROXY}"
nph="${nph//,./,*.}"
nph="${nph#,}"
nph="${nph//,/|}"

JAVA_TOOL_OPTIONS="-Dhttp.proxyHost=$host -Dhttp.proxyPort=$port -Dhttps.proxyHost=$host -Dhttps.proxyPort=$port -Dhttp.nonProxyHosts=$nph"

cat > "$PROXY_ENV" <<EOF
# $GENERATED_MARK from .env — do not edit.
export HTTP_PROXY="$HTTP_PROXY"
export HTTPS_PROXY="$HTTP_PROXY"
export http_proxy="$HTTP_PROXY"
export https_proxy="$HTTP_PROXY"
export NO_PROXY="$NO_PROXY"
export no_proxy="$NO_PROXY"
export JAVA_TOOL_OPTIONS="$JAVA_TOOL_OPTIONS"
EOF

mkdir -p "$(dirname "$M2_SETTINGS")"
cat > "$M2_SETTINGS" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!-- $GENERATED_MARK from .env — do not edit. -->
<settings xmlns="http://maven.apache.org/SETTINGS/1.2.0"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.2.0 https://maven.apache.org/xsd/settings-1.2.0.xsd">
  <proxies>
    <proxy>
      <id>env-http</id>
      <active>true</active>
      <protocol>http</protocol>
      <host>${host}</host>
      <port>${port}</port>
      <nonProxyHosts>${nph}</nonProxyHosts>
    </proxy>
    <proxy>
      <id>env-https</id>
      <active>true</active>
      <protocol>https</protocol>
      <host>${host}</host>
      <port>${port}</port>
      <nonProxyHosts>${nph}</nonProxyHosts>
    </proxy>
  </proxies>
</settings>
EOF
echo "[setup-proxy] wrote $PROXY_ENV and $M2_SETTINGS (proxy ${host}:${port}, nonProxyHosts ${nph})"
